product_specs = [
            {
                "slug": "hukuju-matcha",
                "name": "Kiyona Matcha",
                "brand": "Kettl",
                "preparation": "latte",
                "image_url": "https://kettl.co/cdn/shop/files/599d9ca7-61cd-42af-a698-afd20169922c.jpg?v=1762973476&width=1200",
                "product_url": "https://kettl.co/products/hukuju-matcha-1?variant=47783373734138",
                "tags": ["nutty", "grassy", "verdant"],
            },
            {
                "slug": "kiyona-matcha",
                "name": "Kiyona Matcha",
                "brand": "Kettl",
                "preparation": "usucha",
                "image_url": "https://kettl.co/cdn/shop/files/3591029d-cbe4-4bee-b85e-3ac3eb4dbee0_1680x.jpg?v=1755114175",
                "product_url": "https://kettl.co/products/kiyona-matcha?pr_prod_strat=e5_desc&pr_rec_id=a3ad54589&pr_rec_pid=8667352629498&pr_ref_pid=8098143666426&pr_seq=uniform",
                "tags": ["astringent", "cocoa", "nutty"],
            },
            {
                "slug": "kohata-matcha",
                "name": "Kohata Matcha",
                "brand": "Kettl",
                "preparation": "koicha",
                "image_url": "https://kettl.co/cdn/shop/files/4b86217c-e836-4027-a489-170dbe9514ae_1680x.jpg?v=1755022395",
                "product_url": "https://kettl.co/collections/matcha-green-tea/products/kohata-matcha-20g",
                "tags": ["oceanic", "savory", "umami"],
            },
            {
                "slug": "yamagumo-matcha",
                "name": "Yamagumo Matcha",
                "brand": "Kettl",
                "preparation": "usucha",
                "image_url": "https://kettl.co/cdn/shop/files/2a9f4b9a-5227-4211-b208-83f94887f5c4_1680x.jpg?v=1752611694",
                "product_url": "https://kettl.co/products/yamagumo-matcha?_pos=5&_sid=fbb9e8347&_ss=r",
                "tags": ["astringent", "verdant"],
            },
            {
                "slug": "suiteki-matcha",
                "name": "Suiteki Matcha",
                "brand": "Kettl",
                "preparation": "latte",
                "image_url": "https://kettl.co/cdn/shop/files/cae314a4-d872-4e09-8366-e7b036c135d6.jpg?v=1764165969&width=1200",
                "product_url": "https://kettl.co/products/suiteki-matcha-100g?variant=48006817906938",
                "tags": ["nutty", "grassy"],
            },
            {
                "slug": "sayaka",
                "name": "Sayaka",
                "brand": "Ippodo",
                "preparation": "usucha",
                "image_url": "https://ippodotea.com/cdn/shop/files/ippodo-tea-sayaka-matcha-plate.jpg?v=1761798292&width=600",
                "product_url": "https://ippodotea.com/collections/matcha/products/sayaka-no-mukashi",
                "tags": ["creamy", "sweet", "umami", "astringent"],
            },
            {
                "slug": "ummon",
                "name": "Ummon",
                "brand": "Ippodo",
                "preparation": "koicha",
                "image_url": "https://ippodotea.com/cdn/shop/files/ippodo-tea-ummon-matcha-plate.jpg?v=1761797795&width=600",
                "product_url": "https://ippodotea.com/collections/matcha/products/ummon-no-mukashi-40g",
                "tags": ["sweet", "umami", "astringent"],
            },
            {
                "slug": "kan",
                "name": "Kan",
                "brand": "Ippodo",
                "preparation": "latte",
                "image_url": "https://ippodotea.com/cdn/shop/files/ippodo-tea-kan-matcha-plate.jpg?v=1761833799&width=600",
                "product_url": "https://ippodotea.com/collections/matcha/products/kan-20",
                "tags": ["umami", "sweet", "astringent"],
            },
            {
                "slug": "ikuyo",
                "name": "Ikuyo",
                "brand": "Ippodo",
                "preparation": "latte",
                "image_url": "https://ippodotea.com/cdn/shop/files/ippodo-tea-ikuyo-matcha-plate.jpg?v=1763055331&width=600",
                "product_url": "https://ippodotea.com/collections/matcha/products/ikuyo-20",
                "tags": ["astringent", "umami", "sweet"],
            },
            {
                "slug": "wakaki",
                "name": "Wakaki",
                "brand": "Ippodo",
                "preparation": "usucha",
                "image_url": "https://ippodotea.com/cdn/shop/files/ippodo-tea-wakaki-matcha-plate.jpg?v=1761783548&width=600",
                "product_url": "https://ippodotea.com/collections/matcha/products/wakaki-20g-box",
                "tags": ["umami", "astringent", "sweet"],
            },
            {
                "slug": "rockys-matcha-ceremonial-blend-matcha",
                "name": "Ceremonial Blend",
                "brand": "Rocky's Matcha",
                "preparation": "latte",
                "image_url": "https://www.rockysmatcha.com/cdn/shop/files/Swipe_Re-Edit.jpg?v=1760692987&width=3000",
                "product_url": "https://www.rockysmatcha.com/products/rockys-matcha-ceremonial-blend-matcha-100g",
                "tags": ["rich", "savory"],
            },
            {
                "slug": "rockys-matcha-osada-ceremonial-blend",
                "name": "Osada Ceremonial Blend",
                "brand": "Rocky's Matcha",
                "preparation": "latte",
                "image_url": "https://www.rockysmatcha.com/cdn/shop/files/Rocky_sOct2024Photo7.2Large.jpg?crop=center&height=863&v=1763596042&width=720",
                "product_url": "https://www.rockysmatcha.com/products/rockys-matcha-osada-ceremonial-blend-matcha-20g",
                "tags": ["silky", "roasted"],
            },
            {
                "slug": "rockys-matcha-Shiranami-ceremonial-blend",
                "name": "Shiranami Ceremonial Blend",
                "brand": "Rocky's Matcha",
                "preparation": "usucha",
                "image_url": "https://www.rockysmatcha.com/cdn/shop/files/rocky_smatchaShiranamiCeremonialBlendMatcha100g2-min.jpg?crop=center&height=863&v=1760685401&width=720",
                "product_url": "https://www.rockysmatcha.com/products/rockys-matcha-shiranami-ceremonial-blend-matcha-20g",
                "tags": ["vegetal", "umami"],
            },
            {
                "slug": "rockys-matcha-organic-Kogacha",
                "name": "Organic Kogacha",
                "brand": "Rocky's Matcha",
                "preparation": "latte",
                "image_url": "https://www.rockysmatcha.com/cdn/shop/files/rocky_smatchaOrganicKogachaBlend20g2_a3e7b55b-c92f-4539-9c31-320f547b13f3.jpg?crop=center&height=863&v=1760683638&width=720",
                "product_url": "https://www.rockysmatcha.com/products/rocky-s-matcha-organic-kogacha-blend-20g",
                "tags": ["sweet", "umami", "chocolate"],
            },
            {
                "slug": "rockys-matcha-koshun",
                "name": "Single Cultivar Koshun",
                "brand": "Rocky's Matcha",
                "preparation": "latte",
                "image_url": "https://www.rockysmatcha.com/cdn/shop/files/koshun-Rocky_sMatcha_May2024_Photo_Round100022.jpg?crop=center&height=863&v=1715825029&width=720",
                "product_url": "https://www.rockysmatcha.com/products/rockys-matcha-single-cultivar-koshun-matcha-20g",
                "tags": ["grassy", "earthy", "sweet"],
            },
            {
                "slug": "rockys-matcha-asahi",
                "name": "Single Cultivar Asahi",
                "brand": "Rocky's Matcha",
                "preparation": "latte",
                "image_url": "https://www.rockysmatcha.com/cdn/shop/files/rocky_s_matcha_Single_Cultivar_Asahi_Matcha_20g_2-min.png?crop=center&height=863&v=1760621056&width=720",
                "product_url": "https://www.rockysmatcha.com/products/rockys-matcha-single-cultivar-asahi-matcha-20g",
                "tags": ["umami", "vanilla"],
            },
            {
                "slug": "rockys-matcha-horii-shichimeien-narino",
                "name": "Horii Shichimeien Narino",
                "brand": "Rocky's Matcha",
                "preparation": "usucha",
                "image_url": "https://www.rockysmatcha.com/cdn/shop/files/Narino_Ball_2-White-min.jpg?crop=center&height=863&v=1760692723&width=720",
                "product_url": "https://www.rockysmatcha.com/products/rockys-matcha-single-cultivar-narino-matcha-20g",
                "tags": ["umami", "rich", "floral"],
            },

            {
                "slug": "tezumi-umezuki-uji-okumidori-matcha",
                "name": "Umezuki - Uji Okumidori Matcha",
                "brand": "Tezumi",
                "preparation": "usucha",
                "image_url": "https://www.tezumi.com/cdn/shop/files/Umezuki-Split.jpg?v=1727182422",
                "product_url": "https://www.tezumi.com/collections/matcha/products/umezuki-matcha",
                "tags": ["aromatic", "sweet", "umami"],
            },
            {
                "slug": "tezumi-uji-samidori-matcha",
                "name": "Uji Samidori Matcha",
                "brand": "Tezumi",
                "preparation": "koicha",
                "image_url": "https://www.tezumi.com/cdn/shop/products/Samidori-1.jpg?v=1762268825&width=840",
                "product_url": "https://www.tezumi.com/collections/matcha/products/uji-samidori-matcha?_pos=6&_fid=d312af6da&_ss=c",
                "tags": ["sweet", "aromatic", "umami"],
            },
            {
                "slug": "tezumi-ungetsu-no-shiro-uji-matcha",
                "name": "Ungetsu-no-Shiro - Uji Matcha",
                "brand": "Tezumi",
                "preparation": "usucha",
                "image_url": "https://www.tezumi.com/cdn/shop/files/Ungetsu-no-shiro-TopSQ-Web.jpg?v=1744314017&width=840",
                "product_url": "https://www.tezumi.com/collections/matcha/products/ungetsu-no-shiro-uji-matcha?_pos=7&_fid=c311a55de&_ss=c",
                "tags": ["aromatic", "umami", "sweet"],
            },
            {
                "slug": "tezumi-wazuka-saemidori-matcha",
                "name": "Wazuka Saemidori Matcha",
                "brand": "Tezumi",
                "preparation": "latte",
                "image_url": "https://www.tezumi.com/cdn/shop/files/Azuma-Saemidori-Matcha-top_3e208c5f-4ed3-4d80-8f75-3d628c41f1cc.jpg?v=1759170099&width=840",
                "product_url": "https://www.tezumi.com/collections/lattes-and-mixed-drinks/products/wazuka-saemidori-matcha",
                "tags": ["aromatic", "umami", "sweet"],
            },     
            {
                "slug": "meiko-ceremonial-matcha",
                "name": "Meiko™ Ceremonial Matcha",
                "brand": "Matchaeologist",
                "preparation": "latte",
                "image_url": "https://www.matchaeologist.com/cdn/shop/products/P-01_1024x1024.jpg?v=1487288229",
                "product_url": "https://www.matchaeologist.com/products/meiko-ceremonial-matcha?srsltid=AfmBOophHDiNmVeBfMC_UK7oLzN1Cfls2uOWo1LlIly5I6xyyFdjmE3u",
                "tags": ["floral", "sweet", "savory", "astringent"],
            },
            {
                "slug": "midori-spring-organic-ceremonial-matcha-emerald",
                "name": "Organic Ceremonial Matcha Emerald",
                "brand": "Midori Spring",
                "preparation": "latte",
                "image_url": "https://www.midorispring.com/cdn/shop/files/MidoriEmeraldMatcha2023DarkTinv3yellowish.jpg?v=1762911959&width=1500",
                "product_url": "https://www.midorispring.com/products/ceremonial-emerald-class-organic-matcha",
                "tags": ["roasted", "astringent", "creamy"],
            },
            {
                "slug": "midori-spring-organic-ceremonial-matcha-gold",
                "name": "Organic Ceremonial Matcha Gold",
                "brand": "Midori Spring",
                "preparation": "koicha",
                "image_url": "https://www.midorispring.com/cdn/shop/files/MSGoldDarkTin2023Main_93fcad4e-71f7-477e-bc02-f7b9180c070e.jpg?v=1762974417&width=1100",
                "product_url": "https://www.midorispring.com/products/ceremonial-gold-class-organic-matcha-green-tea",
                "tags": ["floral", "sweet", "umami"],
            },
            {
                "slug": "midori-spring-rare-ceremonial-matcha-miru-limited",
                "name": "Rare Ceremonial Matcha - Miru Limited",
                "brand": "Midori Spring",
                "preparation": "koicha",
                "image_url": "https://www.midorispring.com/cdn/shop/files/MIRUDarkTin2023E8E0B1.jpg?v=1712590234&width=1100",
                "product_url": "https://www.midorispring.com/products/rare-ceremonial-matcha-miru-limited-30g",
                "tags": ["umami", "sweet", "toasted"],
            },
        ]