# Generated by Django 6.0 on 2026-01-19 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProductMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_matches",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-match_percentage"],
            },
        ),
    ]
