# Generated by Django 6.0 on 2026-01-19 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taste_profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tasteprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taste_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tasteprofiledetail",
            name="archetype",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="taste_profile_details",
                to="taste_profiles.tasteprofilearchetype",
            ),
        ),
        migrations.AddField(
            model_name="tasteprofiledetail",
            name="taste_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="taste_profiles.tasteprofile",
            ),
        ),
        migrations.AddField(
            model_name="tasteprofileflavordimension",
            name="characteristic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taste_profile_dimensions",
                to="taste_profiles.flavorcharacteristic",
            ),
        ),
        migrations.AddField(
            model_name="tasteprofileflavordimension",
            name="taste_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flavor_dimensions",
                to="taste_profiles.tasteprofile",
            ),
        ),
        migrations.AddField(
            model_name="tasteprofile",
            name="flavor_characteristics",
            field=models.ManyToManyField(
                blank=True,
                related_name="taste_profiles",
                through="taste_profiles.TasteProfileFlavorDimension",
                through_fields=("taste_profile", "characteristic"),
                to="taste_profiles.flavorcharacteristic",
            ),
        ),
        migrations.AddIndex(
            model_name="flavorcharacteristic",
            index=models.Index(
                fields=["parent"], name="taste_profi_parent__883b29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flavorcharacteristic",
            index=models.Index(
                fields=["is_active", "parent"], name="taste_profi_is_acti_e35da2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tasteprofileflavordimension",
            index=models.Index(
                fields=["taste_profile"], name="taste_profi_taste_p_447a7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tasteprofileflavordimension",
            index=models.Index(
                fields=["characteristic"], name="taste_profi_charact_b3cf72_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tasteprofileflavordimension",
            constraint=models.UniqueConstraint(
                fields=("taste_profile", "characteristic"),
                name="unique_profile_characteristic_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="tasteprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_system", True), ("user__isnull", True)),
                    models.Q(("is_system", False), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="tasteprofile_user_or_system",
            ),
        ),
    ]
