# Generated by Django 6.0 on 2026-02-09 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taste_profiles", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasteprofiledetail",
            old_name="dimension",
            new_name="detail_type",
        ),
    ]
