# Generated by Django 6.0 on 2026-01-19 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewsubpreference",
            name="bucket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subpreferences",
                to="reviews.reviewpreference",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="preference_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="reviews.reviewsubpreference",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="unique_user_product_review"
            ),
        ),
    ]
