# Generated by Django 6.0 on 2026-01-19 20:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taste_profiles", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preparation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(blank=True, max_length=255)),
                ("image_url", models.URLField(blank=True)),
                ("product_url", models.URLField(blank=True)),
                (
                    "preparation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.preparation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductTaste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intensity",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_tastes",
                        to="products.product",
                    ),
                ),
                (
                    "taste_dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_tastes",
                        to="taste_profiles.flavorcharacteristic",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="taste_dimensions",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                through="products.ProductTaste",
                to="taste_profiles.flavorcharacteristic",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.tag"
            ),
        ),
        migrations.AddIndex(
            model_name="producttaste",
            index=models.Index(
                fields=["taste_dimension"], name="products_pr_taste_d_50eeed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producttaste",
            index=models.Index(
                fields=["product"], name="products_pr_product_3fce5b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttaste",
            constraint=models.UniqueConstraint(
                fields=("product", "taste_dimension"),
                name="uniq_product_taste_dimension",
            ),
        ),
    ]
