# Generated by Django 6.0 on 2026-02-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("taste_profiles", "0003_rename_dimension_tasteprofiledetail_detail_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="producttaste",
            name="uniq_product_taste_dimension",
        ),
        migrations.RemoveIndex(
            model_name="producttaste",
            name="products_pr_taste_d_50eeed_idx",
        ),
        migrations.RenameField(
            model_name="producttaste",
            old_name="taste_dimension",
            new_name="taste_characteristic",
        ),
        migrations.AddIndex(
            model_name="producttaste",
            index=models.Index(
                fields=["taste_characteristic"], name="products_pr_taste_c_e964ed_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttaste",
            constraint=models.UniqueConstraint(
                fields=("product", "taste_characteristic"),
                name="uniq_product_taste_characteristic",
            ),
        ),
    ]
